---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: >-
      Build resources for openshift-provision-manager and
      openshift-provision-runner.
  name: openshift-provision-manager-build

parameters:
- name: GIT_REPO
  value: https://github.com/gnuthought/openshift-provision-manager.git
- name: NAMESPACE
  value: openshift

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/display-name: CentOS
    name: centos
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        description: CentOS 7 base image
        openshift.io/display-name: CentOS 7
        openshift.io/provider-display-name: CentOS 7
      from:
        kind: DockerImage
        name: docker.io/centos:7
      importPolicy: {}
      name: "7"
      referencePolicy:
        type: Local

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: openshift-provision-manager
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: openshift-provision-runner
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: openshift-provision-manager
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-provision-manager:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: manager
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
    triggers: []

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: openshift-provision-runner
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-provision-runner:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: runner
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        buildArgs:
        - name: OPENSHIFT_PROVISION_REPO
          value: https://github.com/gnuthought/ansible-role-openshift-provision
        from:
          kind: ImageStreamTag
          name: centos:7
    triggers: []
