---
apiVersion: v1
kind: BuildConfig
metadata:
  name: openshift-provision-manager
  namespace: openshift
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-provision-manager:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: centos:7
        namespace: openshift
  triggers: []
