---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: CentOS
  name: centos
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: CentOS 7 base image
      openshift.io/display-name: CentOS 7
      openshift.io/provider-display-name: CentOS 7
    from:
      kind: DockerImage
      name: docker.io/centos:7
    importPolicy: {}
    name: "7"
    referencePolicy:
      type: Local
