---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: openshift-provision-manager
  name: manager
  namespace: openshift-provision
spec:
  replicas: 1
  selector:
    matchLabels:
      component: openshift-provision-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: openshift-provision-manager
    spec:
      containers:
      - name: manager
        image: docker-registry.default.svc:5000/openshift/openshift-provision-manager:latest
        imagePullPolicy: Always
        #livenessProbe:
        #readinessProbe:
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/openshift-provision/cache
          name: cache
      restartPolicy: Always
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache
