---
- name: OpenShift Provision
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load default main vars
    include_vars:
      dir: "{{ vars_dir }}"
      files_matching: 'main\.(json|ya?ml)$'
    vars:
      vars_dir: "{{ openshift_provision_config_path }}/default/vars"
    when: vars_dir is directory

  - name: Load cluster main vars
    include_vars:
      dir: "{{ vars_dir }}"
      files_matching: 'main\.(json|ya?ml)$'
    vars:
      vars_dir: >-
        {{ openshift_provision_config_path
         ~ '/cluster/'
         ~ openshift_provision_cluster_name | default('')
         ~ '/vars'
        }}
    when: vars_dir is directory

  - name: Load vars in hierarchy order
    include_vars:
      dir: "{{ vars_dir }}"
      files_matching: '[a-z0-9].*\.(json|ya?ml)$'
    with_items: >-
      {{ (openshift_provision_config_hierarchy|default([]))[::-1] }}
    vars:
      vars_dir: "{{ openshift_provision_config_path }}/{{ item }}/vars"
    when: vars_dir is directory

  - name: Load vars without hierarchy
    include_vars:
      dir: "{{ openshift_provision_config_path }}"
      files_matching: '[a-z0-9].*\.(json|ya?ml)$'
    when: openshift_provision_config_hierarchy is not defined

  roles:
  - role: openshift-provision
