---
- name: OpenShift Provision
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: Show openshift_provision_config_path
    debug:
      var: openshift_provision_config_path

  - name: Load vars files from openshift_provision_config_path
    include_vars:
      file: "{{ item }}"
    # Load in reverse order so earlier path items override later ones
    with_items: "{{ openshift_provision_config_path[::-1] }}"
    when: item is file

  - name: Load vars directories from openshift_provision_config_path
    include_vars:
      dir: "{{ item }}"
      files_matching: 'main\.(json|ya?ml)$'
    with_items: "{{ openshift_provision_config_path[::-1] }}"
    when: item is directory

  - name: Load vars in openshift_provision_config_hierarchy
    include_vars:
      dir: "{{ item }}"
      files_matching: '[a-z0-9].*\.(json|ya?ml)$'
    with_items: >-
      {{ (openshift_provision_config_hierarchy|default([]))[::-1] }}
    when: item is directory

  - name: Set openshift_provision_resource_path by openshift_provision_config_hierarchy
    set_fact:
      openshift_provision_resource_path: >-
        {{ openshift_provision_config_hierarchy|default([])
         | map('regex_replace','^(.*)$', openshift_provision_config_path ~ '/\1/resources')
         | list
        }}
    when: openshift_provision_resource_path is not defined

  - name: Include openshift-provision role
    include_role:
      name: openshift-provision
